# Generated by Django 5.1.3 on 2024-11-17 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='langchainpgembedding',
            name='dtype',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
